# Generated by Django 5.2.17 on 2026-09-22 13:23

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.ShopUserManager()),
            ],
        ),
    ]
