# Generated by Django 5.2.17 on 2026-09-08 12:31

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_indexes_and_rls'),
        ('tenants', '0002_initial'),
        ('warehouse', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('code', models.CharField(help_text='Yetkazib beruvchi hujjatidagi partiya raqami', max_length=60, verbose_name='Partiya kodi')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Yaroqlilik muddati')),
                ('produced_at', models.DateField(blank=True, null=True, verbose_name='Ishlab chiqarilgan sana')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Partiya',
                'verbose_name_plural': 'Partiyalar',
                'ordering': ['expiry_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, verbose_name='Miqdor')),
                ('reason', models.CharField(choices=[('purchase', 'Yetkazib beruvchidan kirim'), ('return_from_customer', 'Mijozdan qaytdi'), ('manual_add', "Qo'lda kiritildi"), ('opening_balance', "Boshlang'ich qoldiq"), ('sale', 'Sotuv'), ('return_to_supplier', 'Yetkazib beruvchiga qaytarildi'), ('manual_remove', "Qo'lda chiqarildi"), ('transfer_out', "Ko'chirish: jo'natildi"), ('transfer_in', "Ko'chirish: qabul qilindi"), ('transit_loss', "Yo'lda yo'qolgan"), ('stocktake_correction', 'Inventarizatsiya farqi'), ('write_off_damaged', 'Buzilgan tovar hisobdan chiqarildi'), ('write_off_expired', "Muddati o'tgan tovar hisobdan chiqarildi")], max_length=30, verbose_name='Sababi')),
                ('unit_cost', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Birlik tannarxi')),
                ('currency', models.CharField(blank=True, max_length=3, verbose_name='Valyuta')),
                ('document_type', models.CharField(blank=True, max_length=30, verbose_name='Hujjat turi')),
                ('document_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Hujjat ID')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name="Qo'shimcha")),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Sodir bo'lgan vaqt")),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.batch', verbose_name='Partiya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Kim')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.variant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Qoldiq harakati',
                'verbose_name_plural': 'Qoldiq harakatlari',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, default=0, max_digits=18, verbose_name='Qoldiq')),
                ('reserved_quantity', apps.core.fields.QuantityField(decimal_places=3, default=0, max_digits=18, positive=True, verbose_name='Band qilingan')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='stock.batch', verbose_name='Partiya')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.variant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='warehouse.warehouse', verbose_name='Ombor')),
                ('last_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.stockmovement', verbose_name='Oxirgi harakat')),
            ],
            options={
                'verbose_name': 'Qoldiq',
                'verbose_name_plural': 'Qoldiqlar',
                'ordering': ['variant__product__name', 'warehouse__name'],
            },
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['tenant', 'expiry_date'], name='stock_batch_tenant__2ef766_idx'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('tenant', 'variant', 'code'), name='unique_variant_batch_code'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'variant', 'warehouse', 'batch'], name='stock_stock_tenant__88a090_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'occurred_at'], name='stock_stock_tenant__3fe9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'document_type', 'document_id'], name='stock_stock_tenant__44f952_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='movement_quantity_not_zero'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'variant'], name='stock_stock_tenant__daffc6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['tenant', 'warehouse'], name='stock_stock_tenant__1e47ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('tenant', 'variant', 'warehouse', 'batch'), name='unique_stock_balance', nulls_distinct=False),
        ),
    ]
