# Generated by Django 5.2.17 on 2026-09-16 06:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Raqami')),
                ('subtotal', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Chegirmasiz summa')),
                ('discount_total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Chegirma')),
                ('total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Jami')),
                ('cash_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Naqd')),
                ('card_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Karta')),
                ('status', models.CharField(choices=[('completed', 'Yakunlangan'), ('voided', 'Bekor qilingan')], default='completed', max_length=10, verbose_name='Holati')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('fiscal_receipt_id', models.CharField(blank=True, max_length=64, verbose_name='Fiskal chek raqami')),
                ('fiscal_qr_url', models.URLField(blank=True, verbose_name='Fiskal QR havolasi')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Kassir')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to=settings.AUTH_USER_MODEL, verbose_name='Kim bekor qildi')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Narxi')),
                ('discount_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Chegirma')),
                ('line_total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Qator summasi')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Birlik tannarxi')),
                ('line_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Qator tannarxi')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Sotuv')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Sotuv qatori',
                'verbose_name_plural': 'Sotuv qatorlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Raqami')),
                ('total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Qaytarilgan summa')),
                ('refund_method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta')], default='cash', max_length=10, verbose_name='Qaytarish usuli')),
                ('fiscal_receipt_id', models.CharField(blank=True, max_length=64, verbose_name='Fiskal chek raqami')),
                ('fiscal_qr_url', models.URLField(blank=True, verbose_name='Fiskal QR havolasi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_returns', to=settings.AUTH_USER_MODEL, verbose_name='Kim qabul qildi')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.sale', verbose_name='Sotuv')),
            ],
            options={
                'verbose_name': 'Qaytarish',
                'verbose_name_plural': 'Qaytarishlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Birlik tannarxi')),
                ('refund_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Qaytariladigan summa')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline', verbose_name='Sotuv qatori')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salereturn', verbose_name='Qaytarish')),
            ],
            options={
                'verbose_name': 'Qaytarish qatori',
                'verbose_name_plural': 'Qaytarish qatorlari',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status', '-created_at'], name='sales_sale_status_c95ece_idx'),
        ),
    ]
