# Generated by Django 5.2.17 on 2026-09-16 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='request_key',
            field=models.UUIDField(blank=True, help_text="Kassa yuboradigan bir martalik kalit: tugma ikki marta bosilsa ham ikkinchi so'rov yangi hujjat yaratmaydi", null=True, unique=True, verbose_name='So‘rov kaliti'),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='request_key',
            field=models.UUIDField(blank=True, help_text="Kassa yuboradigan bir martalik kalit: tugma ikki marta bosilsa ham ikkinchi so'rov yangi hujjat yaratmaydi", null=True, unique=True, verbose_name='So‘rov kaliti'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['cashier', '-created_at'], name='sales_sale_cashier_62c037_idx'),
        ),
    ]
