# Generated by Django 5.2.17 on 2026-09-22 06:00

import django.db.models.deletion
from django.db import migrations, models


def fill_location(apps, schema_editor):
    """Eski cheklar bitta joyda sotilgan — u endi ombor deb yoziladi."""
    Location = apps.get_model('inventory', 'Location')
    Sale = apps.get_model('sales', 'Sale')

    warehouse = Location.objects.filter(kind='warehouse').order_by('pk').first()

    if warehouse is not None:
        Sale.objects.filter(location__isnull=True).update(location=warehouse)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_location_transfer_transferline_variantstock_and_more'),
        ('sales', '0002_sale_request_key_salereturn_request_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='inventory.location', verbose_name='Joy'),
        ),
        migrations.RunPython(fill_location, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sale',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sales',
                to='inventory.location',
                verbose_name='Joy',
            ),
        ),
    ]
