# Generated by Django 5.2.17 on 2026-09-08 10:49

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('code', models.CharField(help_text='Qisqa belgi, hujjat raqamlarida ishlatiladi. Masalan: MARKAZ', max_length=20, verbose_name='Kodi')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('goods_type', models.CharField(choices=[('universal', 'Universal'), ('electronics', 'Texnika'), ('clothing', 'Kiyim-kechak'), ('food', 'Oziq-ovqat'), ('household', 'Maishiy mollar'), ('construction', 'Qurilish mollari')], default='universal', max_length=20, verbose_name='Tovar turi')),
                ('purpose', models.CharField(choices=[('main', 'Asosiy ombor'), ('retail', 'Savdo nuqtasi'), ('transit', 'Tranzit')], default='main', help_text='Tranzit omboridagi tovar sotuvga chiqmaydi', max_length=20, verbose_name='Vazifasi')),
                ('manager', models.CharField(blank=True, max_length=150, verbose_name="Mas'ul shaxs")),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('area', apps.core.fields.QuantityField(blank=True, decimal_places=3, max_digits=18, null=True, positive=True, verbose_name='Maydoni, m²')),
                ('capacity', apps.core.fields.QuantityField(blank=True, decimal_places=3, help_text="Taxminiy sig'im, birliklarda", max_digits=18, null=True, positive=True, verbose_name="Sig'imi")),
                ('temperature', models.CharField(blank=True, help_text='Masalan: +10°C / +25°C', max_length=50, verbose_name='Harorat rejimi')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Ombor',
                'verbose_name_plural': 'Omborlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('level', models.CharField(choices=[('view', "Ko'rish"), ('operate', 'Kirim-chiqim qilish'), ('manage', "To'liq boshqarish")], default='view', max_length=20, verbose_name='Daraja')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_access', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Omborga kirish',
                'verbose_name_plural': 'Omborga kirish huquqlari',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_warehouse_code'),
        ),
        migrations.AddIndex(
            model_name='warehouseaccess',
            index=models.Index(fields=['user'], name='warehouse_w_user_id_8633e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='warehouseaccess',
            constraint=models.UniqueConstraint(fields=('warehouse', 'user'), name='unique_warehouse_user_access'),
        ),
    ]
