# Generated by Django 5.2.17 on 2026-09-08 09:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('role', models.CharField(choices=[('owner', 'Egasi'), ('manager', 'Menejer'), ('storekeeper', 'Omborchi'), ('salesperson', 'Sotuvchi'), ('viewer', 'Kuzatuvchi')], default='viewer', max_length=20, verbose_name='Rol')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "A'zolik",
                'verbose_name_plural': "A'zoliklar",
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('slug', models.SlugField(help_text='Lotin harflari, raqam va chiziqcha. Hisobotlarda ishlatiladi.', max_length=60, unique=True, verbose_name='Qisqa nomi')),
                ('business_type', models.CharField(choices=[('construction', 'Qurilish mollari'), ('clothing', 'Kiyim-kechak'), ('grocery', 'Oziq-ovqat'), ('general', 'Aralash / boshqa')], default='general', help_text="Boshlang'ich o'lchov birliklari va kategoriyalarni tanlash uchun", max_length=20, verbose_name='Faoliyat turi')),
                ('base_currency', models.CharField(default='UZS', help_text='Hisobotlar shu valyutada jamlanadi', max_length=3, verbose_name='Asosiy valyuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['name'],
            },
        ),
    ]
