# Generated by Django 5.2.17 on 2026-09-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Manzil'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='expiry_warning_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Muddat tugashiga shuncha kun qolganda ogohlantiriladi', verbose_name='Yaroqlilik ogohlantirishi, kun'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='inn',
            field=models.CharField(blank=True, max_length=20, verbose_name='INN'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='purchase_prefix',
            field=models.CharField(default='KIR', max_length=10, verbose_name='Kirim prefiksi'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sale_prefix',
            field=models.CharField(default='SOT', max_length=10, verbose_name='Sotuv prefiksi'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='transfer_prefix',
            field=models.CharField(default='KOCH', max_length=10, verbose_name="Ko'chirish prefiksi"),
        ),
    ]
