# Generated by Django 5.2.17 on 2026-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_address_tenant_expiry_warning_days_tenant_inn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.JSONField(blank=True, help_text='Bo‘sh — rolning standart ruxsatlari', null=True, verbose_name='Ruxsatlar'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Egasi'), ('manager', 'Menejer'), ('storekeeper', 'Omborchi'), ('salesperson', 'Sotuvchi / kassir'), ('accountant', 'Buxgalter'), ('viewer', 'Kuzatuvchi')], default='viewer', max_length=20, verbose_name='Rol'),
        ),
    ]
