# Generated by Django 5.2.17 on 2026-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_membership_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='credit_markup_default',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qarzga sotuv formasida oldindan to‘ldiriladi', max_digits=6, verbose_name='Kredit ustamasi, %'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='debt_default_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Qarzga sotuvda to‘lov muddati ko‘rsatilmasa', verbose_name='Qarz muddati, kun'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='debt_prefix',
            field=models.CharField(default='QRZ', max_length=10, verbose_name='Qarz prefiksi'),
        ),
    ]
