# Generated by Django 5.2.17 on 2026-09-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_credit_markup_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='actual_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Haqiqiy manzil'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Hisob raqami'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='code',
            field=models.CharField(blank=True, max_length=8, verbose_name='Kod'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='director',
            field=models.CharField(blank=True, max_length=150, verbose_name='Rahbar'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_form',
            field=models.CharField(choices=[('llc', 'MChJ'), ('ip', 'YaTT'), ('jsc', 'AJ'), ('pe', 'XK'), ('other', 'Boshqa')], default='llc', max_length=10, verbose_name='Huquqiy shakli'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant-logos/', verbose_name='Logotip'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='mfo',
            field=models.CharField(blank=True, max_length=5, verbose_name='MFO'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ro‘yxatdan o‘tish raqami'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qisqa nom'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vat_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='QQS to‘lovchi kodi'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Veb-sayt'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Yuridik manzil'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('code',), name='unique_tenant_code'),
        ),
    ]
