# Generated by Django 5.2.17 on 2026-09-16 06:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('shop_name', models.CharField(default='Do‘kon', max_length=120, verbose_name='Do‘kon nomi')),
                ('label_width_mm', models.PositiveSmallIntegerField(default=40, verbose_name='Yorliq eni, mm')),
                ('label_height_mm', models.PositiveSmallIntegerField(default=30, verbose_name='Yorliq bo‘yi, mm')),
                ('max_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Kassir bera oladigan eng katta chegirma, %')),
            ],
            options={
                'verbose_name': 'Do‘kon sozlamalari',
                'verbose_name_plural': 'Do‘kon sozlamalari',
            },
        ),
    ]
