# Generated by Django 5.2.17 on 2026-09-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_page_height_mm',
            field=models.PositiveSmallIntegerField(default=110, verbose_name='Chek sahifasi bo‘yi, mm'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='receipt_width_mm',
            field=models.PositiveSmallIntegerField(default=80, verbose_name='Chek qog‘ozi eni, mm'),
        ),
    ]
