# Generated by Django 5.2.17 on 2026-09-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopsettings_receipt_page_height_mm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='price_rounding_step',
            field=models.PositiveIntegerField(default=1000, verbose_name='Narxni yaxlitlash qadami, so‘m'),
        ),
    ]
