# Generated by Django 5.2.17 on 2026-10-09 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shopsettings_price_rounding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='cabinet_columns',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(26)], verbose_name='Shkaf ustunlari'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='cabinet_rows',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Shkaf qatorlari'),
        ),
    ]
