# Generated by Django 5.2.17 on 2026-10-10 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_shopsettings_cabinet_columns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsettings',
            name='cabinet_columns',
        ),
        migrations.RemoveField(
            model_name='shopsettings',
            name='cabinet_rows',
        ),
    ]
