# Generated by Django 5.2.17 on 2026-09-08 11:25

import apps.catalog.fields
import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_extensions'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('path', apps.catalog.fields.LtreeField(blank=True, editable=False, null=True, verbose_name="Yo'l")),
                ('default_unit', models.CharField(blank=True, max_length=30, verbose_name='Standart birlik')),
                ('code_prefix', models.CharField(blank=True, max_length=10, verbose_name='Kod prefiksi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='Yuqori kategoriya')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('key', models.CharField(help_text='JSONB kaliti. Masalan: qalinlik, rang, olcham', max_length=50, verbose_name='Kalit')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('value_type', models.CharField(choices=[('text', 'Matn'), ('number', 'Son'), ('choice', "Ro'yxatdan tanlash"), ('boolean', "Ha / yo'q")], default='text', max_length=20, verbose_name='Qiymat turi')),
                ('unit', models.CharField(blank=True, help_text='Son atributlar uchun. Masalan: mm, kg', max_length=30, verbose_name="O'lchov birligi")),
                ('choices', models.JSONField(blank=True, default=list, help_text='"Ro\'yxatdan tanlash" turi uchun qiymatlar ro\'yxati', verbose_name='Tanlovlar')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='Standart qiymat')),
                ('is_required', models.BooleanField(default=False, verbose_name='Majburiy')),
                ('is_variant_axis', models.BooleanField(default=False, help_text="Belgilansa, bu atribut bo'yicha alohida variantlar hosil bo'ladi", verbose_name="Variant o'qi")),
                ('uniqueness', models.PositiveSmallIntegerField(choices=[(0, 'Talab qilinmaydi'), (1, 'Tashkilot ichida unikal')], default=0, verbose_name='Unikallik')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': "Atribut ta'rifi",
                'verbose_name_plural': "Atribut ta'riflari",
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('name', models.CharField(max_length=250, verbose_name='Nomi')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brend')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('base_unit', models.CharField(blank=True, help_text='Qoldiq shu birlikda hisoblanadi. Masalan: kg, dona, m2', max_length=30, verbose_name='Asosiy birlik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategoriya')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Variant nomi')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributlar')),
                ('purchase_price', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Kirim narxi')),
                ('sale_price', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Sotuv narxi')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('min_stock', apps.core.fields.QuantityField(blank=True, decimal_places=3, help_text='Shundan kam qolganda ogohlantiriladi', max_digits=18, null=True, positive=True, verbose_name='Minimal qoldiq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Mahsulot')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['product__name', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('unit', models.CharField(help_text='Registrdagi birlik nomi. Masalan: qop, palet', max_length=30, verbose_name='Birlik')),
                ('factor_to_base', apps.core.fields.FactorField(decimal_places=6, help_text='1 birlik necha asosiy birlikka teng. Masalan qop uchun 50', max_digits=18, verbose_name='Asosiy birlikka koeffitsient')),
                ('is_default_purchase', models.BooleanField(default=False, verbose_name='Kirimda standart')),
                ('is_default_sale', models.BooleanField(default=False, verbose_name='Sotuvda standart')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': "O'ram birligi",
                'verbose_name_plural': "O'ram birliklari",
                'ordering': ['unit'],
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('code', models.CharField(max_length=100, verbose_name='Kod')),
                ('code_normalized', models.CharField(db_index=True, editable=False, max_length=100, verbose_name='Normallashtirilgan kod')),
                ('code_type', models.CharField(choices=[('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('code128', 'Code 128'), ('internal', 'Ichki kod'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Turi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Shtrix-kod',
                'verbose_name_plural': 'Shtrix-kodlar',
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('tenant', 'parent', 'name'), name='unique_category_name_in_parent'),
        ),
        migrations.AddConstraint(
            model_name='attributedefinition',
            constraint=models.UniqueConstraint(fields=('category', 'key'), name='unique_attribute_key_in_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tenant', 'category'], name='catalog_pro_tenant__48a14c_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['tenant', 'product'], name='catalog_var_tenant__7d3008_idx'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('tenant', 'sku'), name='unique_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(fields=('variant', 'unit'), name='unique_variant_unit'),
        ),
        migrations.AddConstraint(
            model_name='barcode',
            constraint=models.UniqueConstraint(fields=('tenant', 'code_normalized'), name='unique_tenant_barcode'),
        ),
    ]
