# Generated by Django 5.2.17 on 2026-09-16 06:15

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Rang',
                'verbose_name_plural': 'Ranglar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nomi')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'O‘lcham',
                'verbose_name_plural': 'O‘lchamlar',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Brend')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('sale_price', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Sotuv narxi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('sku', models.CharField(max_length=40, unique=True, verbose_name='Artikul')),
                ('barcode', models.CharField(max_length=32, unique=True, verbose_name='Shtrix-kod')),
                ('sale_price', apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Sotuv narxi')),
                ('average_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='O‘rtacha tannarx')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Qoldiq')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='Minimal qoldiq')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.color', verbose_name='Rang')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Mahsulot')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.size', verbose_name='O‘lcham')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['product__name', 'size__position', 'color__name'],
                'indexes': [models.Index(fields=['barcode'], name='catalog_var_barcode_ef6240_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'size', 'color'), name='unique_product_size_color', nulls_distinct=False)],
            },
        ),
    ]
