# Generated by Django 5.2.17 on 2026-09-17 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stock_not_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mxik_code',
            field=models.CharField(blank=True, help_text='17 xonali raqam. Mahsulotda o‘ziniki bo‘lmasa shu ishlatiladi.', max_length=17, validators=[django.core.validators.RegexValidator(message='MXIK kodi 17 xonali raqamdan iborat bo‘lishi kerak.', regex='^\\d{17}$')], verbose_name='MXIK kodi'),
        ),
        migrations.AddField(
            model_name='category',
            name='package_code',
            field=models.CharField(blank=True, help_text='Soliq ma’lumotnomasidagi o‘ram kodi (ixtiyoriy).', max_length=20, verbose_name='Qadoq kodi'),
        ),
        migrations.AddField(
            model_name='product',
            name='mxik_code',
            field=models.CharField(blank=True, help_text='Bo‘sh bo‘lsa kategoriyaning kodi ishlatiladi.', max_length=17, validators=[django.core.validators.RegexValidator(message='MXIK kodi 17 xonali raqamdan iborat bo‘lishi kerak.', regex='^\\d{17}$')], verbose_name='MXIK kodi'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Qadoq kodi'),
        ),
    ]
