# Generated by Django 5.2.17 on 2026-09-22 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_images_slug_and_color_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='mxik_code',
        ),
        migrations.RemoveField(
            model_name='category',
            name='package_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mxik_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='package_code',
        ),
    ]
