# Generated by Django 5.2.17 on 2026-09-08 13:20

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('unit', models.CharField(blank=True, help_text="Bo'sh bo'lsa mahsulotning bazaviy birligi", max_length=30, verbose_name='Birlik')),
                ('factor', apps.core.fields.FactorField(decimal_places=6, default=1, help_text='1 birlik necha bazaviy birlikka teng', max_digits=18, verbose_name='Koeffitsient')),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name='Miqdor')),
                ('quantity_base', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name='Bazaviy miqdor')),
                ('unit_price', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Birlik narxi')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma, %')),
                ('line_total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18, verbose_name='Qator summasi')),
                ('line_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18, verbose_name='Qator tannarxi')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hujjat qatori',
                'verbose_name_plural': 'Hujjat qatorlari',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('kind', models.CharField(choices=[('purchase', 'Kirim'), ('sale', 'Sotuv'), ('return_in', 'Mijozdan qaytish'), ('return_out', 'Yetkazib beruvchiga qaytarish')], max_length=20, verbose_name='Turi')),
                ('number', models.CharField(max_length=40, verbose_name='Raqami')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('external_number', models.CharField(blank=True, max_length=60, verbose_name='Tashqi hujjat raqami')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('total_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18, verbose_name='Summa')),
                ('total_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18, verbose_name='Tannarx')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
