# Generated by Django 5.2.17 on 2026-09-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_indexes_and_rls'),
        ('documents', '0001_initial'),
        ('partners', '0001_initial'),
        ('stock', '0002_append_only_and_rls'),
        ('tenants', '0002_initial'),
        ('warehouse', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='partners.partner', verbose_name='Kontragent'),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='warehouse.warehouse', verbose_name='Ombor'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='stock.batch', verbose_name='Partiya'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.document', verbose_name='Hujjat'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot'),
        ),
        migrations.AddField(
            model_name='documentline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_lines', to='catalog.variant', verbose_name='Variant'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'kind', '-date'], name='documents_d_tenant__391381_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='documents_d_tenant__1461e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_tenant_document_number'),
        ),
        migrations.AddIndex(
            model_name='documentline',
            index=models.Index(fields=['tenant', 'document'], name='documents_d_tenant__08a46c_idx'),
        ),
    ]
