# Generated by Django 5.2.17 on 2026-09-09 06:25

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_indexes_and_rls'),
        ('documents', '0003_enable_rls'),
        ('stock', '0002_append_only_and_rls'),
        ('tenants', '0002_initial'),
        ('warehouse', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('number', models.CharField(max_length=40, verbose_name='Raqami')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sent', "Jo'natilgan"), ('received', 'Qabul qilingan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Jo'natilgan vaqt")),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Qabul qilingan vaqt')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='Kim yaratdi')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouse.warehouse', verbose_name='Qayerdan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouse.warehouse', verbose_name='Qayerga')),
                ('transit_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_transit', to='warehouse.warehouse', verbose_name='Tranzit ombor')),
            ],
            options={
                'verbose_name': "Ko'chirish",
                'verbose_name_plural': "Ko'chirishlar",
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='Birlik')),
                ('factor', apps.core.fields.FactorField(decimal_places=6, default=1, max_digits=18, verbose_name='Koeffitsient')),
                ('quantity_sent', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name="Jo'natildi")),
                ('quantity_sent_base', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name="Jo'natildi (bazaviy)")),
                ('quantity_received', apps.core.fields.QuantityField(blank=True, decimal_places=3, max_digits=18, null=True, positive=True, verbose_name='Qabul qilindi')),
                ('quantity_received_base', apps.core.fields.QuantityField(blank=True, decimal_places=3, max_digits=18, null=True, positive=True, verbose_name='Qabul qilindi (bazaviy)')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='stock.batch', verbose_name='Partiya')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents.transfer', verbose_name="Ko'chirish")),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': "Ko'chirish qatori",
                'verbose_name_plural': "Ko'chirish qatorlari",
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['tenant', 'status', '-date'], name='documents_t_tenant__83cc61_idx'),
        ),
        migrations.AddConstraint(
            model_name='transfer',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_tenant_transfer_number'),
        ),
        migrations.AddIndex(
            model_name='transferline',
            index=models.Index(fields=['tenant', 'transfer'], name='documents_t_tenant__ebe4ce_idx'),
        ),
    ]
