# Generated by Django 5.2.17 on 2026-09-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_transfer_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='credit_markup_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Kredit ustamasi, %'),
        ),
        migrations.AddField(
            model_name='document',
            name='customer_document',
            field=models.CharField(blank=True, max_length=60, verbose_name='Mijoz hujjati'),
        ),
        migrations.AddField(
            model_name='document',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mijoz ismi'),
        ),
        migrations.AddField(
            model_name='document',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mijoz telefoni'),
        ),
        migrations.AddField(
            model_name='document',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='To‘lov muddati'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_credit',
            field=models.BooleanField(default=False, verbose_name='Qarzga'),
        ),
        migrations.AddField(
            model_name='document',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma'), ('mixed', 'Aralash'), ('deferred', 'Keyinroq')], default='cash', max_length=20, verbose_name='To‘lov usuli'),
        ),
    ]
