# Generated by Django 5.2.17 on 2026-09-16 06:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('date', models.DateField(verbose_name='Sanasi')),
                ('category', models.CharField(choices=[('rent', 'Ijara'), ('salary', 'Ish haqi'), ('utilities', 'Kommunal'), ('other', 'Boshqa')], default='other', max_length=15, verbose_name='Turi')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
            ],
            options={
                'verbose_name': 'Xarajat',
                'verbose_name_plural': 'Xarajatlar',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
