# Generated by Django 5.2.17 on 2026-09-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_membership_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('action', models.CharField(choices=[('create', 'Qo‘shildi'), ('update', 'O‘zgartirildi'), ('delete', 'O‘chirildi'), ('confirm', 'Tasdiqlandi'), ('cancel', 'Bekor qilindi'), ('send', 'Jo‘natildi'), ('receive', 'Qabul qilindi'), ('adjust', 'Qo‘lda tuzatildi'), ('stocktake', 'Inventarizatsiya'), ('payment', 'To‘lov qabul qilindi'), ('sync', 'Sinxronlandi'), ('import', 'Import qilindi')], max_length=20, verbose_name='Amal')),
                ('object_type', models.CharField(max_length=40, verbose_name='Obyekt turi')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(blank=True, max_length=250, verbose_name='Obyekt')),
                ('warehouse_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Ombor ID')),
                ('warehouse_name', models.CharField(blank=True, max_length=150, verbose_name='Ombor')),
                ('user_name', models.CharField(blank=True, max_length=150, verbose_name='Foydalanuvchi')),
                ('details', models.CharField(blank=True, max_length=500, verbose_name='Tafsilot')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='O‘zgarishlar')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Amal',
                'verbose_name_plural': 'Amallar tarixi',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='audit_audit_tenant__eab6aa_idx'), models.Index(fields=['tenant', 'user', '-created_at'], name='audit_audit_tenant__7f4051_idx'), models.Index(fields=['tenant', 'object_type', 'object_id'], name='audit_audit_tenant__ac5f72_idx')],
            },
        ),
    ]
