# Generated by Django 5.2.17 on 2026-09-14 15:11

import apps.core.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_document_credit_markup_percent_and_more'),
        ('partners', '0002_enable_rls'),
        ('tenants', '0005_tenant_credit_markup_default_and_more'),
        ('warehouse', '0002_enable_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('number', models.CharField(max_length=40, verbose_name='Raqami')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Mijoz')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('customer_document', models.CharField(blank=True, max_length=60, verbose_name='Hujjat')),
                ('issued_date', models.DateField(verbose_name='Qarz sanasi')),
                ('due_date', models.DateField(verbose_name='To‘lov muddati')),
                ('base_amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Asosiy summa')),
                ('markup_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Ustama, %')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Qarz summasi')),
                ('paid_amount', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=18, verbose_name='To‘langan')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('paid', 'To‘langan'), ('cancelled', 'Bekor qilingan')], default='active', max_length=20, verbose_name='Holati')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='To‘liq yopilgan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='documents.document', verbose_name='Sotuv hujjati')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='partners.partner', verbose_name='Kontragent')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Summa')),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', 'O‘tkazma')], default='cash', max_length=20, verbose_name='To‘lov usuli')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='To‘langan vaqt')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('request_key', models.CharField(blank=True, max_length=64, verbose_name='So‘rov kaliti')),
                ('created_by_name', models.CharField(blank=True, max_length=150, verbose_name='Qabul qildi')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Qabul qildi')),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='debts.debt', verbose_name='Qarz')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Qarz to‘lovi',
                'verbose_name_plural': 'Qarz to‘lovlari',
                'ordering': ['paid_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='debts_debt_tenant__076585_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['tenant', 'partner'], name='debts_debt_tenant__a83e11_idx'),
        ),
        migrations.AddConstraint(
            model_name='debt',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='unique_tenant_debt_number'),
        ),
        migrations.AddConstraint(
            model_name='debtpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key', ''), _negated=True), fields=('tenant', 'request_key'), name='unique_debt_payment_request'),
        ),
    ]
