# Generated by Django 5.2.17 on 2026-09-16 06:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Raqami')),
                ('date', models.DateField(verbose_name='Sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan')], default='draft', max_length=10, verbose_name='Holati')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='catalog.category', verbose_name='Kategoriya')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL, verbose_name='Kim boshladi')),
            ],
            options={
                'verbose_name': 'Inventarizatsiya',
                'verbose_name_plural': 'Inventarizatsiyalar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('reason', models.CharField(max_length=300, verbose_name='Sababi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='write_offs', to=settings.AUTH_USER_MODEL, verbose_name='Kim yozdi')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Hisobdan chiqarish',
                'verbose_name_plural': 'Hisobdan chiqarishlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(default=0, verbose_name='Kutilgan')),
                ('counted_quantity', models.IntegerField(default=0, verbose_name='Sanaldi')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount', verbose_name='Inventarizatsiya')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Sanoq qatori',
                'verbose_name_plural': 'Sanoq qatorlari',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('stock_count', 'variant'), name='unique_variant_in_stock_count')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Miqdor')),
                ('reason', models.CharField(choices=[('purchase', 'Kirim'), ('purchase_cancel', 'Kirim bekor qilindi'), ('sale', 'Sotuv'), ('sale_void', 'Sotuv bekor qilindi'), ('return', 'Qaytarish'), ('count_adjustment', 'Inventarizatsiya tuzatishi'), ('write_off', 'Hisobdan chiqarish')], max_length=20, verbose_name='Sabab')),
                ('document_type', models.CharField(blank=True, max_length=20, verbose_name='Hujjat turi')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hujjat raqami')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Birlik tannarxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to=settings.AUTH_USER_MODEL, verbose_name='Xodim')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='inventory_s_variant_608d8a_idx')],
            },
        ),
    ]
