# Generated by Django 5.2.17 on 2026-09-22 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Sum


def create_locations(apps, schema_editor):
    """Ikkita joy yaratadi va eski yozuvlarni omborga bog'laydi.

    Ilgari qoldiq bitta edi — joy tushunchasi yo'q edi. O'sha qoldiq
    endi **ombor** qoldig'i hisoblanadi; zalga chiqarilgani ko'chirish
    hujjati bilan yoziladi. Namuna ma'lumot uchun `seed_demo --force`
    ikkala joyni ham to'ldiradi.
    """
    Location = apps.get_model('inventory', 'Location')
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockCount = apps.get_model('inventory', 'StockCount')
    WriteOff = apps.get_model('inventory', 'WriteOff')
    VariantStock = apps.get_model('inventory', 'VariantStock')

    warehouse, _ = Location.objects.get_or_create(
        kind='warehouse', defaults={'name': 'Ombor'}
    )
    Location.objects.get_or_create(kind='shop', defaults={'name': 'Do‘kon'})

    StockMovement.objects.filter(location__isnull=True).update(location=warehouse)
    StockCount.objects.filter(location__isnull=True).update(location=warehouse)
    WriteOff.objects.filter(location__isnull=True).update(location=warehouse)

    # Joydagi qoldiq keshi jurnaldan yig'iladi
    totals = (
        StockMovement.objects.values('variant_id', 'location_id')
        .annotate(total=Sum('quantity'))
        .order_by()
    )

    VariantStock.objects.bulk_create([
        VariantStock(
            variant_id=row['variant_id'],
            location_id=row['location_id'],
            quantity=row['total'] or 0,
        )
        for row in totals
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_mxik_codes'),
        ('inventory', '0002_movement_append_only'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nomi')),
                ('kind', models.CharField(choices=[('warehouse', 'Ombor'), ('shop', 'Do‘kon')], max_length=10, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Joy',
                'verbose_name_plural': 'Joylar',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Raqami')),
                ('date', models.DateField(verbose_name='Sanasi')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Ko‘chirish',
                'verbose_name_plural': 'Ko‘chirishlar',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
            ],
            options={
                'verbose_name': 'Ko‘chirish qatori',
                'verbose_name_plural': 'Ko‘chirish qatorlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Qoldiq')),
            ],
            options={
                'verbose_name': 'Joydagi qoldiq',
                'verbose_name_plural': 'Joydagi qoldiqlar',
                'ordering': ['location_id', 'variant_id'],
            },
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Kirim'), ('purchase_cancel', 'Kirim bekor qilindi'), ('sale', 'Sotuv'), ('sale_void', 'Sotuv bekor qilindi'), ('return', 'Qaytarish'), ('count_adjustment', 'Sanoq tuzatishi'), ('write_off', 'Hisobdan chiqarish'), ('transfer_out', 'Ko‘chirildi (chiqdi)'), ('transfer_in', 'Ko‘chirildi (kirdi)')], max_length=20, verbose_name='Sabab'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.location', verbose_name='Joy'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.location', verbose_name='Joy'),
        ),
        migrations.AddField(
            model_name='writeoff',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_offs', to='inventory.location', verbose_name='Joy'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['location', '-created_at'], name='inventory_s_locatio_aaf296_idx'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to=settings.AUTH_USER_MODEL, verbose_name='Kim ko‘chirdi'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.location', verbose_name='Qayerdan'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.location', verbose_name='Qayerga'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.transfer', verbose_name='Ko‘chirish'),
        ),
        migrations.AddField(
            model_name='transferline',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_lines', to='catalog.variant', verbose_name='Variant'),
        ),
        migrations.AddField(
            model_name='variantstock',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventory.location', verbose_name='Joy'),
        ),
        migrations.AddField(
            model_name='variantstock',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='catalog.variant', verbose_name='Variant'),
        ),
        migrations.AddIndex(
            model_name='variantstock',
            index=models.Index(fields=['location', 'variant'], name='inventory_v_locatio_585ab1_idx'),
        ),
        migrations.AddConstraint(
            model_name='variantstock',
            constraint=models.UniqueConstraint(fields=('variant', 'location'), name='unique_variant_location'),
        ),
        migrations.RunPython(create_locations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='movements',
                to='inventory.location',
                verbose_name='Joy',
            ),
        ),
        migrations.AlterField(
            model_name='stockcount',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stock_counts',
                to='inventory.location',
                verbose_name='Joy',
            ),
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='write_offs',
                to='inventory.location',
                verbose_name='Joy',
            ),
        ),
    ]
