# Generated by Django 5.2.17 on 2026-10-10 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variantstock_cell'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Bitta harf: A, B, C…', max_length=1, unique=True, verbose_name='Harfi')),
                ('name', models.CharField(max_length=60, verbose_name='Qayerda')),
                ('shelves', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Javonlar soni')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Tartibi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Javon qatori',
                'verbose_name_plural': 'Javon qatorlari',
                'ordering': ['position', 'code'],
            },
        ),
    ]
