# Generated by Django 5.2.17 on 2026-09-08 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('is_supplier', models.BooleanField(default=False, verbose_name='Yetkazib beruvchi')),
                ('is_customer', models.BooleanField(default=False, verbose_name='Mijoz')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='INN')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact', models.CharField(blank=True, max_length=150, verbose_name='Aloqa shaxsi')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Manzil')),
                ('bank', models.CharField(blank=True, max_length=250, verbose_name='Bank rekvizitlari')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Kontragent',
                'verbose_name_plural': 'Kontragentlar',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'is_supplier'], name='partners_pa_tenant__f83993_idx'), models.Index(fields=['tenant', 'is_customer'], name='partners_pa_tenant__6d030f_idx')],
            },
        ),
    ]
