# Generated by Django 5.2.17 on 2026-09-08 12:53

import apps.core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_indexes_and_rls'),
        ('stock', '0002_append_only_and_rls'),
        ('tenants', '0002_initial'),
        ('warehouse', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('quantity_initial', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name="Boshlang'ich miqdor")),
                ('quantity_remaining', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name='Qolgan miqdor')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Birlik tannarxi')),
                ('currency', models.CharField(max_length=3, verbose_name='Valyuta')),
                ('unit_cost_base', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Tannarx (asosiy valyutada)')),
                ('exchange_rate', apps.core.fields.FactorField(decimal_places=6, default=1, max_digits=18, verbose_name='Kurs')),
                ('acquired_at', models.DateTimeField(verbose_name='Kirim vaqti')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='stock.batch', verbose_name='Partiya')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='stock.stockmovement', verbose_name='Manba harakati')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='catalog.variant', verbose_name='Variant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_layers', to='warehouse.warehouse', verbose_name='Ombor')),
            ],
            options={
                'verbose_name': 'Tannarx qatlami',
                'verbose_name_plural': 'Tannarx qatlamlari',
                'ordering': ['acquired_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CostConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('quantity', apps.core.fields.QuantityField(decimal_places=3, max_digits=18, positive=True, verbose_name='Miqdor')),
                ('unit_cost_base', apps.core.fields.MoneyField(decimal_places=2, max_digits=18, verbose_name='Birlik tannarxi (asosiy valyutada)')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_consumptions', to='stock.stockmovement', verbose_name='Chiqim harakati')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='pricing.costlayer', verbose_name='Qatlam')),
            ],
            options={
                'verbose_name': 'Tannarx sarfi',
                'verbose_name_plural': 'Tannarx sarflari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('code', models.CharField(help_text='UZS, USD, EUR', max_length=3, verbose_name='Kodi')),
                ('name', models.CharField(max_length=60, verbose_name='Nomi')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='Belgisi')),
                ('is_base', models.BooleanField(default=False, verbose_name='Asosiy valyuta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
                'ordering': ['-is_base', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('rate', apps.core.fields.FactorField(decimal_places=6, help_text='1 birlik valyuta necha asosiy valyutaga teng', max_digits=18, verbose_name='Kurs')),
                ('valid_from', models.DateField(verbose_name='Amal qila boshlaydi')),
                ('source', models.CharField(blank=True, help_text="Masalan: Markaziy bank, qo'lda", max_length=60, verbose_name='Manba')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='pricing.currency', verbose_name='Valyuta')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddIndex(
            model_name='costlayer',
            index=models.Index(fields=['tenant', 'variant', 'warehouse', 'batch', 'acquired_at'], name='cost_layer_fifo_idx'),
        ),
        migrations.AddConstraint(
            model_name='costlayer',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_initial'))), name='layer_remaining_not_over_initial'),
        ),
        migrations.AddIndex(
            model_name='costconsumption',
            index=models.Index(fields=['tenant', 'movement'], name='pricing_cos_tenant__ec5302_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='unique_tenant_currency'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('tenant',), name='single_base_currency_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['tenant', 'currency', '-valid_from'], name='pricing_exc_tenant__65248f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('currency', 'valid_from'), name='unique_rate_per_day'),
        ),
    ]
