# Generated by Django 5.2.17 on 2026-09-16 06:15

import apps.core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('name', models.CharField(max_length=150, verbose_name='Nomi')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Ta’minotchi',
                'verbose_name_plural': 'Ta’minotchilar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Raqami')),
                ('date', models.DateField(verbose_name='Sanasi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('confirmed', 'Tasdiqlangan'), ('cancelled', 'Bekor qilingan')], default='draft', max_length=10, verbose_name='Holati')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('total', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='Summa')),
                ('amount_paid', apps.core.fields.MoneyField(decimal_places=2, default=0, max_digits=14, verbose_name='To‘langan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan vaqt')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Bekor qilingan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchases.supplier', verbose_name='Ta’minotchi')),
            ],
            options={
                'verbose_name': 'Kirim',
                'verbose_name_plural': 'Kirimlar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Miqdor')),
                ('unit_cost', apps.core.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Birlik tannarxi')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase', verbose_name='Kirim')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.variant', verbose_name='Variant')),
            ],
            options={
                'verbose_name': 'Kirim qatori',
                'verbose_name_plural': 'Kirim qatorlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan')),
                ('date', models.DateField(verbose_name='Sanasi')),
                ('amount', apps.core.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Izoh')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to=settings.AUTH_USER_MODEL, verbose_name='Kim kiritdi')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.supplier', verbose_name='Ta’minotchi')),
            ],
            options={
                'verbose_name': 'Ta’minotchiga to‘lov',
                'verbose_name_plural': 'Ta’minotchiga to‘lovlar',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status', '-date'], name='purchases_p_status_b25f36_idx'),
        ),
    ]
