# Generated by Django 5.2.17 on 2026-09-21 11:54

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='new_sale_price',
            field=apps.core.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Yangi sotuv narxi'),
        ),
    ]
