# Generated by Django 5.2.17 on 2026-10-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchase_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='cell',
            field=models.CharField(blank=True, max_length=3, verbose_name='Shkafdagi joyi'),
        ),
    ]
