# Generated by Django 5.2.17 on 2026-10-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseline_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='to_shop',
            field=models.PositiveIntegerField(default=0, verbose_name='Shundan zalga'),
        ),
    ]
