# Generated by Django 5.2.17 on 2026-09-08 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
                ('name', models.CharField(help_text='Lotin harflari va pastki chiziq. Masalan: mashina, katta_qop', max_length=50, verbose_name='Nomi')),
                ('symbol', models.CharField(blank=True, help_text='Qisqartma, ixtiyoriy. Masalan: msh', max_length=10, verbose_name='Belgisi')),
                ('definition', models.CharField(help_text='Mavjud birliklar orqali. Masalan: 6 * m3', max_length=100, verbose_name="Ta'rifi")),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': "O'lchov birligi",
                'verbose_name_plural': "O'lchov birliklari",
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_unit_name'), models.UniqueConstraint(condition=models.Q(('symbol', ''), _negated=True), fields=('tenant', 'symbol'), name='unique_tenant_unit_symbol')],
            },
        ),
    ]
